apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-tqqg
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-tqqg
    app.kubernetes.io/part-of: integ-app-yzld
  name: hacbs-test-project-tqqg
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-tqqg
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-tqqg
    spec:
      containers:
      - image: quay.io/bootstrap/nbe-e2e-wlef-tenant/integ-app-yzld/hacbs-test-project-tqqg@sha256:6b87c2c3fd4d37dd08ab6f38e920648ac636bab9b229bfc2be20a037ffe5c26b
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
