apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-tqqg
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - env:
        - name: var_name
          value: test
        image: quay.io/bootstrap/nbe-e2e-wlef-tenant/integ-app-yzld/hacbs-test-project-tqqg@sha256:6b87c2c3fd4d37dd08ab6f38e920648ac636bab9b229bfc2be20a037ffe5c26b
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
